name: Publish

on:
  push:
    branches:
      - main

jobs:
  Publish:
    runs-on: ubuntu-18.04

    env:
      S3_BASE_URL: s3://dl.eidu.com/

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run unit tests
        run: ./gradlew testReleaseUnitTest

      - name: Publish test reports
        uses: actions/upload-artifact@v1
        with:
          name: test-reports
          path: content-app-library/build/reports
        if: ${{ failure() }}

      - name: Build AAR
        run: ./gradlew build --stacktrace

      - name: Publish AAR
        run: ./gradlew publish --stacktrace
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

      - name: Determine version
        run: echo "VERSION_NAME=`./gradlew -q printVersion | tail -n 1`" >> $GITHUB_ENV

      - name: Publish Javadoc
        run: |
          ./gradlew javadoc --stacktrace
          export S3_OBJECT_PATH=dev/content-app-library/"$VERSION_NAME"/javadoc
          aws s3 cp content-app-library/build/docs/javadoc "$S3_BASE_URL$S3_OBJECT_PATH" --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_UPLOAD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_UPLOAD_SECRET_ACCESS_KEY }}
